### ISSUE TITLE
pageWriteの文字数について

### ISSUE THREAD

**Issue by nopnop2002** [Tamakichi/Arduino-W25Q64#3]
こんにちは
ライブラリの公開、ありがとうございます。

uint16_t W25Q64_pageWrite(uint16_t sect_no, uint16_t inaddr, byte* data, byte n)

この関数の最後の引数がbyte型になっています。
byte型は0から255までの8bitの数値を格納しますが、
W25Q64のPage Program(0x02)では、一度に最大256バイトまで書き込めると思います。

ご確認ください。

**Comment by Tamakichi** [comment]
こんにちは、
ご指摘ありがとうございます。
本件修正しました。
